2020-04-20 09:07:49,727 [INFO] root consoleworker.py:434	Log file created
2020-04-20 09:07:49,729 [INFO] root consoleworker.py:438	Logging handler <logging.FileHandler object at 0x7f28229c4c90> added
2020-04-20 09:07:49,730 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7f2822a0a8d0> added
2020-04-20 09:07:49,731 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7f28229b0ad0> added
2020-04-20 09:07:49,733 [INFO] root consoleworker.py:373	Created a folder for the test. /var/loadtest/logs/2020-04-20_09-07-49.671641
2020-04-20 09:07:49,733 [INFO] yandextank.core.tankcore tankcore.py:237	Configuring plugins...
2020-04-20 09:07:49,734 [INFO] yandextank.core.tankcore tankcore.py:190	Loading plugins...
2020-04-20 09:07:49,735 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin phantom from yandextank.plugins.Phantom
2020-04-20 09:07:49,736 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcheck from yandextank.plugins.ResourceCheck
2020-04-20 09:07:49,736 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin json_report from yandextank.plugins.JsonReport
2020-04-20 09:07:49,743 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcassert from yandextank.plugins.RCAssert
2020-04-20 09:07:49,743 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin console from yandextank.plugins.Console
2020-04-20 09:07:49,744 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin shellexec from yandextank.plugins.ShellExec
2020-04-20 09:07:49,745 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin autostop from yandextank.plugins.Autostop
2020-04-20 09:07:49,746 [DEBUG] yandextank.core.tankcore tankcore.py:212	Plugin instances: {'plugin_phantom': <yandextank.plugins.Phantom.plugin.Plugin object at 0x7f28226e7e10>, 'plugin_autostop': <yandextank.plugins.Autostop.plugin.Plugin object at 0x7f28226e7250>, 'plugin_shellexec': <yandextank.plugins.ShellExec.plugin.Plugin object at 0x7f28226e7e50>, 'plugin_console': <yandextank.plugins.Console.plugin.Plugin object at 0x7f28226e7d90>, 'plugin_rcassert': <yandextank.plugins.RCAssert.plugin.Plugin object at 0x7f28226e7ad0>, 'plugin_rcheck': <yandextank.plugins.ResourceCheck.plugin.Plugin object at 0x7f28226e7b50>, 'plugin_json_report': <yandextank.plugins.JsonReport.plugin.Plugin object at 0x7f2822a29a90>}
2020-04-20 09:07:49,748 [DEBUG] yandextank.core.tankcore tankcore.py:244	Configuring <yandextank.plugins.Phantom.plugin.Plugin object at 0x7f28226e7e10>
2020-04-20 09:07:49,750 [DEBUG] yandextank.core.tankcore tankcore.py:391	Searching for plugin: <class 'yandextank.plugins.Autostop.plugin.Plugin'>
2020-04-20 09:07:49,758 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2020-04-20_09-07-49.671641/answ_p9amSV.log
2020-04-20 09:07:49,760 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2020-04-20_09-07-49.671641/phout_7Bklpm.log
2020-04-20 09:07:49,761 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2020-04-20_09-07-49.671641/phantom_stat_Plh9H6.log
2020-04-20 09:07:49,764 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2020-04-20_09-07-49.671641/phantom_nZti0R.log
2020-04-20 09:07:49,765 [DEBUG] yandextank.common.util util.py:479	Trying to resolve address string: auditbase_rest
2020-04-20 09:07:49,767 [DEBUG] yandextank.common.util util.py:516	Parsing port
2020-04-20 09:07:49,773 [DEBUG] yandextank.common.util util.py:527	Lookup result: [(2, 1, 6, '', ('192.168.16.7', 0)), (2, 2, 17, '', ('192.168.16.7', 0)), (2, 3, 0, '', ('192.168.16.7', 0))]
2020-04-20 09:07:49,775 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.16.7 and port 80
2020-04-20 09:07:49,778 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.16.7]:80 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2020-04-20 09:07:49,778 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.16.7]:80
2020-04-20 09:07:49,779 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.16.7]:80
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.16.7]:80, use phantom.connection_test=0 to disable it
2020-04-20 09:07:49,780 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.16.7 and port 80
2020-04-20 09:07:49,781 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.16.7]:80 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2020-04-20 09:07:49,781 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.16.7]:80
2020-04-20 09:07:49,782 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.16.7]:80
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.16.7]:80, use phantom.connection_test=0 to disable it
2020-04-20 09:07:49,783 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.16.7 and port 80
2020-04-20 09:07:49,784 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.16.7]:80 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2020-04-20 09:07:49,786 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.16.7]:80
2020-04-20 09:07:49,787 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.16.7]:80
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.16.7]:80, use phantom.connection_test=0 to disable it
2020-04-20 09:07:49,790 [ERROR] root consoleworker.py:268	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for auditbase_rest, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 555, in resolve
    raise RuntimeError(msg % address_str)

2020-04-20 09:07:49,793 [INFO] root consoleworker.py:269	Trying to clean up
2020-04-20 09:07:49,794 [INFO] yandextank.core.tankcore tankcore.py:561	Releasing lock: /var/lock/lunapark_Htk08g.lock
2020-04-20 09:07:49,802 [WARNING] root consoleworker.py:408	Job number is not available yet
2020-04-20 09:07:49,804 [WARNING] root consoleworker.py:415	Job number is not available yet
2020-04-20 09:07:49,813 [DEBUG] yandextank.core.tankcore tankcore.py:367	Collecting artifacts
2020-04-20 09:07:49,815 [INFO] yandextank.core.tankcore tankcore.py:368	Artifacts dir: /var/loadtest/logs/2020-04-20_09-07-49.671641
2020-04-20 09:07:49,817 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2020-04-20_09-07-49.671641/phantom_nZti0R.log to /var/loadtest/logs/2020-04-20_09-07-49.671641/phantom_nZti0R.log
2020-04-20 09:07:49,822 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2020-04-20_09-07-49.671641/phantom_nZti0R.log
2020-04-20 09:07:49,824 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2020-04-20_09-07-49.671641/answ_p9amSV.log to /var/loadtest/logs/2020-04-20_09-07-49.671641/answ_p9amSV.log
2020-04-20 09:07:49,827 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2020-04-20_09-07-49.671641/answ_p9amSV.log
2020-04-20 09:07:49,829 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2020-04-20_09-07-49.671641/phantom_stat_Plh9H6.log to /var/loadtest/logs/2020-04-20_09-07-49.671641/phantom_stat_Plh9H6.log
2020-04-20 09:07:49,836 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2020-04-20_09-07-49.671641/phantom_stat_Plh9H6.log
2020-04-20 09:07:49,838 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: validation_error.yaml to /var/loadtest/logs/2020-04-20_09-07-49.671641/validation_error.yaml
2020-04-20 09:07:49,841 [WARNING] yandextank.core.tankcore tankcore.py:424	File not found to collect: validation_error.yaml
2020-04-20 09:07:49,843 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2020-04-20_09-07-49.671641/phout_7Bklpm.log to /var/loadtest/logs/2020-04-20_09-07-49.671641/phout_7Bklpm.log
2020-04-20 09:07:49,847 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2020-04-20_09-07-49.671641/phout_7Bklpm.log
